### ISSUE TITLE
XMLData returning input as output as an error response

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#249] opened 2024-01-09 22:01 UTC
For example, XMLData.GetEntryByName(XMLNode.CURSE, 'test123')

returns 'test123'

It's not a table, so you can check for that, but I'd expect something like nil if there's no match.

This becomes an issue here:

XMLData.GetNumEntries(XMLNode.CURSE) -- 16

returns 16

which is incorrect. It's just returning an error response, but since you're expecting an int it looks correct.

For curses, the IDs seem to be the flag values which is probably why it can't count correctly.

XMLData.GetEntryById(16, 1<<0).name : Curse of Darkness!

XMLData.GetEntryById(16, 1<<7).name : Curse of the Giant!

**Comment by laceous** [comment] 2024-01-09 22:11
Update: I just tested XMLData.GetNumEntries(XMLNode.CURSE) a few more times after restarting a couple times, and it returned both 107 and 11. 11 is correct for me with the mods that I have installed.

**Comment by laceous** [comment] 2024-01-09 22:51
I removed my curse mods and did some more testing.

XMLData.GetNumEntries(16) : 8 which is correct

XMLData.GetEntryById(16, 3) : 3 is a "bad" number

XMLData.GetNumEntries(16) : now yields 9 which is incorrect

**Comment by jsgnextortex** [comment] 2024-01-10 01:00
Curses.xml is the absolute worst if you want to iterate over it, so yea...I
dont think this is the right one to do so with the tools we currently have.
Due to the gaps of the ids, specifically.
Now, about the ids themselves, XMLData sues the values used in the console
as ids, since they seem way more friendly than using whatever the fuck the
xmls actually use(which is straight up incompatible with the structure we
use for storing the nodes). I do want to add an xmliterator eventually that
could make this easier.
For the issue with NumEntries returning diffferent values, I wasnt able to
reproduce it locally, sadly, but I'll be on the lookout, if you notice a
particular way to make it pop let me know. Still, again, this is not the
XML you want to use that func on, lol. Btw, if you REALLY need to iterate,
the formula for the ids is "previousid *2" basically.

On another note, you can expect XMLData.GetById and  XMLData.GetByName to
return nil in 1.0.5, I just changed it since, as you said, it didnt make
much sense as it was.

**Comment by laceous** [comment] 2024-01-10 01:23
I imagine a while loop might work better here rather than relying on GetNumEntries in a for loop. Increment the id and use "1 << (id - 1)" as the id value, loop until GetEntryById is nil.

**Comment by laceous** [comment] 2024-01-10 08:28
It seems like you can manipulate GetNumEntries for Achievements too.

XMLData.GetNumEntries(26)
675

XMLData.GetEntryById(26, 1000)
Bad id, fails

XMLData.GetNumEntries(26)
Now 676

XMLData.GetEntryById(26, 1001)
Bad id, fails

XMLData.GetNumEntries(26)
Now 677

**Comment by jsgnextortex** [comment] 2024-01-10 17:22
Oh yea, that did it!, was able to replicate it.
Fixed in 1.0.5

**Closed by jsgnextortex** 2024-01-10 17:22 UTC
Labels: bug, lua
