### ISSUE TITLE
Prevent crashes from simple stage command typos (example: "Stage1")

### ISSUE THREAD

**Issue by orrekorre** [TeamREPENTOGON/REPENTOGON#381] opened 2024-03-18 18:00 UTC

**Comment by jerbmega** [comment] 2024-03-19 12:56
I cannot reproduce this crash at all, typing `Stage1` into the console has no effect. Do you have any more info?

**Comment by jsgnextortex** [comment] 2024-03-19 13:00
it's stage1 with lowercase, the main issue I see is that this request is pretty ambiguous, we can probably reduce the amount of crashes with the stage command by verifying that the stage you are trying to transition exists before actually sending the command, but we definitely dont have a list of all the "simple typos" that can result in a crash to tackle.

**Comment by jsgnextortex** [comment] 2024-03-19 13:35
It's an inconsistent crash, it's not crashing at the game console but rather at our own code (mine, I take the blame for this one, lol). It was an issue with some commands that normally require a space not having one.
Should be fixed on the next release (just pushed a fix on 943d625)

**Closed by jsgnextortex** 2024-03-19 13:35 UTC
