### ISSUE TITLE
RemoveCallback can result in the skip of a callback run of the same time

### ISSUE THREAD

**Issue by jsgnextortex** [TeamREPENTOGON/REPENTOGON#337] opened 2024-02-15 23:09 UTC
Since callbacks are ran in order and can remove themselves, there are situations where removing a callback can result into another callback being skipped entirely.
This issue is also present in vanilla isaac, btw, but it's still horrible.

**Comment by ConnorForan** [comment] 2024-05-24 13:37
Duplicate of https://github.com/TeamREPENTOGON/REPENTOGON/issues/320

**Comment by ConnorForan** [comment] 2024-09-07 00:09
Fixed in https://github.com/TeamREPENTOGON/REPENTOGON/commit/8234c37b67ce104100281a69aa78ce405aaa508a

**Closed by ConnorForan** 2024-09-07 00:09 UTC
Labels: bug, vanilla-tweaks, critical!
